create table if not exists ab_tests (
  id uuid primary key default gen_random_uuid(),
  script text not null,
  product_id text not null,
  model_a text not null,
  model_b text not null,
  video_job_a text,
  video_job_b text,
  video_url_a text,
  video_url_b text,
  adset_id_a text,
  adset_id_b text,
  ad_id_a text,
  ad_id_b text,
  campaign_id text,
  status text not null default 'pending',
  roas_a numeric,
  roas_b numeric,
  winner text,
  started_at timestamptz default now(),
  compare_after timestamptz,
  compared_at timestamptz,
  meta jsonb default '{}',
  created_at timestamptz default now()
);
